services:
  - type: web
    name: ollama-ai-travel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
